### ISSUE TITLE
"TypeError: window.androidWebViewInterface.handleEventFromWebView is not a function

### ISSUE THREAD

**Issue by JamesPJ** [shripalsoni04/nativescript-webview-interface#58]
I'm getting the following error on android 10 `NS{6}`

```
chromium: [INFO:CONSOLE(5)] "TypeError: window.androidWebViewInterface.handleEventFromWebView is not a function
chromium:     at NSWebViewinterface._emitEventToAndroid (https://example.com/js/nativescript-webview-interface.js:139:40)
chromium:     at NSWebViewinterface.emit (https://example.com/js/nativescript-webview-interface.js:156:18)
```

And due to this the emitted events are not getting received.

**Comment by JamesPJ** [comment]
Looks like this package is not maintained anymore. So, got the same feature working using https://www.npmjs.com/package/@nota/nativescript-webview-ext
